package Challenges;

import java.util.ArrayList;
import java.util.Arrays;

public class GuthrieSequence {
    public static void main(String[] args) {
//        ArrayList<Integer> guthrieSequence = GuthrieSequenceGenerator(7);
//        System.out.println(guthrieSequence);
        int result = checkGuthrieSequence(new int[] {8, 4, 2, 1});
        System.out.println(result);
        result = checkGuthrieSequence(new int[] {8, 17, 4, 1});
        System.out.println(result);
        result = checkGuthrieSequence(new int[] {8, 4, 1});
        System.out.println(result);
        result = checkGuthrieSequence(new int[] {8, 4, 2});
        System.out.println(result);
    }


//   create the Guthrie algo function int [] GuthrieSequenceGenerator(int n) // n = a[0];
//  check if the new sequence is equivalent to the sequence generated by GuthrieSequenceGenerator


    public static  int checkGuthrieSequence(int[]a){
        ArrayList<Integer> sequence = GuthrieSequenceGenerator(a[0]);
        ArrayList<Integer> newGuthrie = new ArrayList<>();
        for (int i = 1; i < a.length; i++) {
            newGuthrie.add(a[i]);
        }

        if(newGuthrie.containsAll(sequence)){
            return 1;
        }

        return 0;
    }


    public static ArrayList<Integer> GuthrieSequenceGenerator(int n){
        ArrayList<Integer> gutherieSequence = new ArrayList<>();
                if(n < 0 ) return null;
            while(n != 1) {
                if (n % 2 == 0) {
                    gutherieSequence.add(n = n / 2);

                } else {
                    gutherieSequence.add(n = (n * 3) + 1);
                }
            }

        return gutherieSequence;

    }
}
